### PR TITLE
testing framework

### LINKED ISSUE #3: test-helpers/framework
slipstream should provide tooling for testing connections

this shouldn't be exceptionally hard to implement: the `Slipstream.Test` (or whatever module) should provide functions for sending `Slipstream.Events` directly to the client

we can also add a flag in configuration `test_mode?` (default `false`) which could turn off all `:gun` operations (so the test process does not try to connect to any server)

### PR DESCRIPTION
**Pull request by the-mikedavis**
closes #3 

a nice v0.2.0 release that adds `Slipstream.SocketTest` which is an ExUnit.CaseTemplate you can use to test client behavior

I imagine something like this would be much harder to implement if Slipstream were written differently. The client process and the connection process communicating through events and commands, so we merely need to make the client process _think_ that the test process is the connection process, and then we can simply interact by `assert_receive`ing commands and `send`ing events

### CODE REVIEW

File: lib/slipstream.ex [hunk 1]
```diff
@@ -1286,10 +1285,9 @@ defmodule Slipstream do
   @spec await_reply(push_reference(), timeout()) :: reply() | {:error, :timeout}
   def await_reply(push_reference, timeout \\ @default_timeout)
 
-  def await_reply({topic, ref}, timeout) do
+  def await_reply(ref, timeout) do
     receive do
-      event(%Events.ReplyReceived{ref: ^ref, topic: ^topic} = event) ->
-        Events.ReplyReceived.to_reply(event)
```
Comment (the-mikedavis) [inline lib/slipstream.ex:1292]: this and the associated change in `lib/slipstream/callback:ex:110` are a bit of a refactor: instead of rendering the reply into a common format just before passing it to the user, we do it when we initially map the `%Phoenix.Socket.Message{}` to the `%Slipstream.Events.ReplyReceived{}`

just makes it a bit more DRY and easy-to-use internally (in the library)

File: lib/slipstream/command_router.ex [hunk 2]
```diff
@@ -30,6 +32,10 @@ defmodule Slipstream.CommandRouter do
   @spec route_command(struct()) :: any()
   def route_command(command)
 
+  def route_command(%OpenConnection{config: %Config{test_mode?: true}}) do
+    :ok
+  end
```
Comment (the-mikedavis) [inline lib/slipstream/command_router.ex:37]: if a connection is started in `test_mode?: true`, we do _not_ spawn a connection process for it, so there's no chance that it will attempt to do any network activity

File: lib/slipstream/socket_test.ex [hunk 3]
```diff
@@ -0,0 +1,659 @@
...
+  # the name of the game. We do this with two edits to the usual behavior of a
+  # client:
+  #
+  #   1. do not spawn a connection process with `Slipstream.connect/2`
+  #   2. send a `Slipstream.Events.ChannelConnected` with a pid of the current
+  #      test process
+
+  use ExUnit.CaseTemplate
+
+  import Slipstream.Signatures
```
Comment (the-mikedavis) [inline lib/slipstream/socket_test.ex:100]: I recommend reading through https://hexdocs.pm/slipstream/implementation.html#signatures to learn more about signatures. It's why most things in this module that are `Kernel.send/2`d are wrapped in `event/1` or `command/1`

File: lib/slipstream/socket_test.ex [hunk 4]
```diff
@@ -0,0 +1,659 @@
...
+                           event: unquote(event_expr) = event,
+                           payload: unquote(params_expr) = payload
+                         }),
+                         from
+                       ),
+                       unquote(timeout)
+
+      GenServer.reply(from, ref)
+
+      return
```
Comment (the-mikedavis) [inline lib/slipstream/socket_test.ex:514]: this implementation is a bit fancy because the `%Slipstream.Commands.PushMessage{}` command is sent via `GenServer.call/3` instead of `Kernel.send/2`, because the caller needs a return value from the connection (the `ref`: unique reference for the push) in order to handle replies via `c:Slipstream.handle_reply/3` or `Slipstream.await_reply/2`

the test process is the connection process (genserver) with this testing framework, so we need to fake a regular ole' GenServer call by matching on the signature `{:"$gen_call", from, message}` and replying to that `from` with `GenServer.reply/2` in order to return the ref

File: test/slipstream/socket_test_test.exs [hunk 5]
```diff
@@ -0,0 +1,193 @@
...
+    end
+
+    test "we may connect and join a topic all at once with connect_and_join/5",
+         c do
+      topic = c.topic
+      params = c.params
+
+      join(topic, params)
+
+      connect_and_join @fixture, ^topic, ^params, {:ok, params}
```
Comment (tonyvanriet) [inline test/slipstream/socket_test_test.exs:66]: why `join` AND `connect_and_join`?

File: test/slipstream/socket_test_test.exs [hunk 6]
```diff
@@ -0,0 +1,193 @@
...
+
+      join(topic, params)
+
+      assert_join ^topic, ^params, :ok
+
+      assert_receive {@fixture, :joined, ^topic, %{}}
+
+      # once joined, we do not duplicate the join
+      refute_join ^topic, ^params
+    end
```
Comment (tonyvanriet) [inline test/slipstream/socket_test_test.exs:118]: I'm guessing this is the mindfuck of testing a test framework, but what's going on here? How does `assert_join` "allow" a `:joined` message?

Comment (tonyvanriet) [reply test/slipstream/socket_test_test.exs:118]: I guess I see the `assert_join` macro doing its own `assert_receive` on the join command. ok, ofc, SocketTest is mocking the other end of the socket and sending back a `:joined` event.

so, breaking down the 3 key lines...

```
# I'm the client. join this topic
join(topic, params)

# assert that the socket process sees the join command from above
assert_join ^topic, ^params, :ok

# assert that this test process (the client) sees its :joined confirmation
assert_receive {@fixture, :joined, ^topic, %{}}
```

tell me where I'm being imprecise, or dead wrong...

File: test/slipstream/socket_test_test.exs (hunk 5 above)
Comment (tonyvanriet) [reply test/slipstream/socket_test_test.exs:66]: understanding more after looking more deeply at `assert_join`

should this name be `assert_connect_and_join` or `connect_and_assert_join`?

**Review by tonyvanriet — APPROVED** [review]
looks pretty swanky... but please, no PRs on Monday that test a testing framework

File: test/slipstream/socket_test_test.exs (hunk 5 above)
Comment (the-mikedavis) [reply test/slipstream/socket_test_test.exs:66]: I don't mind that second one

the `join/2` in this case is not from `Slipstream.SocketTest` but from `defp join/2` below

this isn't what it'll look in an actual client test. We have to tell the client to join here because it's just a crappy fixture we want to control imperatively from the tests (in this case with `Kernel.send(fixture, {:join, topic, params})`

`connect_and_join/5` is more meant for clients that attempt to join immediately after connecting

File: test/slipstream/socket_test_test.exs (hunk 6 above)
Comment (the-mikedavis) [reply test/slipstream/socket_test_test.exs:118]: I think I'm gonna rename the `defp join/2` to `defp tell_fixture_to_join/2` because it looks like something that would be provided by Slipstream.SocketTest but it's not

but yep you have the right idea. Check out the fixture in `test/fixtures/test_mode_client.ex`, specifically its implementation of `c:Slipstream.handle_join/3`. It does a `Kernel.send(socket.assigns.test_proc, {__MODULE__, :joined, topic, params})`, which we can assert happened with that `assert_receive/2`

to break it down like you:

```elixir
# tell the client to join the server's "foo" topic
join("foo", params)

# assert that the client is trying to join "foo" and let it join (the `:ok` part)
assert_join "foo", ^params, :ok

# assert that the client was notified that it has joined succesfully
# and that its `c:Slipstream.handle_join/3` callback was invoked
assert_receive {@fixture, :joined, ^topic, %{}}
```

File: test/slipstream/socket_test_test.exs (hunk 5 above)
Comment (the-mikedavis) [reply test/slipstream/socket_test_test.exs]: renamed to `connect_and_assert_join/5`

File: test/slipstream/socket_test_test.exs (hunk 6 above)
Comment (the-mikedavis) [reply test/slipstream/socket_test_test.exs]: renamed that helper to `tell_fixture_to_join/2` and referenced it everywhere with `__MODULE__.tell_fixture_to_join/2` just to make it super clear that it's not imported
